-- The sample source database (see seed.sql) for Oracle. Run as SYSTEM in the container's
-- pluggable database; every statement ends with a line holding only "/".
-- Oracle schemas are users, and Oracle stores unquoted names upper case: CORE, CRM and
-- RESTRICTED (left outside the allowed list by tests).

CREATE USER core NO AUTHENTICATION QUOTA UNLIMITED ON users
/
CREATE USER crm NO AUTHENTICATION QUOTA UNLIMITED ON users
/
CREATE USER restricted NO AUTHENTICATION QUOTA UNLIMITED ON users
/

CREATE TABLE core.customers (
    cust_no     NUMBER(10) CONSTRAINT customers_pkey PRIMARY KEY,
    full_name   VARCHAR2(200) NOT NULL,
    national_id VARCHAR2(30),
    email       VARCHAR2(200),
    phone       VARCHAR2(40),
    branch_code VARCHAR2(10)
)
/
COMMENT ON TABLE core.customers IS 'One row per bank customer'
/
COMMENT ON COLUMN core.customers.national_id IS 'National ID number'
/

CREATE TABLE core.branches (
    branch_code VARCHAR2(10) CONSTRAINT branches_pkey PRIMARY KEY,
    branch_name VARCHAR2(100) NOT NULL
)
/

-- core.customers.branch_code -> core.branches is the one declared relationship.
ALTER TABLE core.customers
    ADD CONSTRAINT customers_branch_fk FOREIGN KEY (branch_code) REFERENCES core.branches (branch_code)
/
ALTER TABLE core.branches ADD CONSTRAINT branches_name_uq UNIQUE (branch_name)
/
CREATE INDEX core.customers_lower_email_idx ON core.customers (LOWER(email))
/

-- accounts.cust_no -> customers.cust_no is NOT declared: inference must find it.
CREATE TABLE core.accounts (
    acct_no   NUMBER(10) CONSTRAINT accounts_pkey PRIMARY KEY,
    cust_no   NUMBER(10) NOT NULL,
    iban      VARCHAR2(40),
    balance   NUMBER(14, 2) DEFAULT 0 NOT NULL,
    opened_on DATE
)
/
CREATE INDEX core.accounts_cust_no_idx ON core.accounts (cust_no)
/

CREATE TABLE core.transactions (
    txn_id  NUMBER(19) CONSTRAINT transactions_pkey PRIMARY KEY,
    acct_no NUMBER(10) NOT NULL,
    amount  NUMBER(14, 2) NOT NULL,
    txn_at  TIMESTAMP WITH TIME ZONE NOT NULL
)
/

-- Arabic table and column names.
CREATE TABLE core."عملاء_محليون" (
    "رقم" NUMBER(10) PRIMARY KEY,
    "الاسم" VARCHAR2(200) NOT NULL,
    "المدينة" VARCHAR2(100)
)
/

CREATE VIEW core.customer_balances AS
    SELECT c.cust_no, c.full_name, SUM(a.balance) AS total_balance
    FROM core.customers c JOIN core.accounts a ON a.cust_no = c.cust_no
    GROUP BY c.cust_no, c.full_name
/

CREATE FUNCTION core.account_turnover(p_acct IN NUMBER) RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT COALESCE(SUM(t.amount), 0) INTO v_total
    FROM core.transactions t JOIN core.accounts a ON a.acct_no = t.acct_no
    WHERE a.acct_no = p_acct;
    RETURN v_total;
END;
/

CREATE PROCEDURE core.close_account(p_acct IN NUMBER) IS
BEGIN
    UPDATE core.accounts a SET balance = 0
    WHERE a.acct_no = p_acct
      AND EXISTS (SELECT 1 FROM core.customers c WHERE c.cust_no = a.cust_no);
END;
/

CREATE TABLE crm.contacts (
    contact_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_no    NUMBER(10),
    notes      VARCHAR2(400)
)
/

CREATE TABLE restricted.salaries (
    emp_id NUMBER(10) PRIMARY KEY,
    salary NUMBER(12, 2) NOT NULL
)
/

INSERT INTO core.branches VALUES ('CAI', 'Cairo Downtown')
/
INSERT INTO core.branches VALUES ('ALX', 'الإسكندرية')
/
INSERT INTO core.customers VALUES (1, 'Amira Hassan', '29001011234567', 'amira.hassan@example.com', '+20 100 123 4567', 'CAI')
/
INSERT INTO core.customers VALUES (2, 'محمد علي', '28505051234568', 'mohamed.ali@example.com', '+20 111 765 4321', 'ALX')
/
INSERT INTO core.customers VALUES (3, 'Sara Ibrahim', NULL, NULL, NULL, 'CAI')
/
INSERT INTO core.accounts VALUES (100, 1, 'EG380019000500000000263180002', 1500.50, DATE '2020-01-15')
/
INSERT INTO core.accounts VALUES (101, 2, 'EG800002000156789012345180002', 320.00, DATE '2021-06-01')
/
INSERT INTO core.accounts VALUES (102, 1, NULL, 0, DATE '2022-03-10')
/
INSERT INTO core.transactions VALUES (1, 100, 200.00, TIMESTAMP '2024-01-01 10:00:00 +00:00')
/
INSERT INTO core.transactions VALUES (2, 100, -50.25, TIMESTAMP '2024-01-02 11:30:00 +00:00')
/
INSERT INTO core.transactions VALUES (3, 101, 75.00, TIMESTAMP '2024-01-03 09:15:00 +00:00')
/
INSERT INTO core."عملاء_محليون" VALUES (1, 'خالد', 'القاهرة')
/
INSERT INTO core."عملاء_محليون" VALUES (2, 'ليلى', NULL)
/
INSERT INTO crm.contacts (cust_no, notes) VALUES (1, 'prefers email')
/
INSERT INTO crm.contacts (cust_no, notes) VALUES (2, NULL)
/
INSERT INTO restricted.salaries VALUES (1, 9000)
/
INSERT INTO restricted.salaries VALUES (2, 12000)
/
COMMIT
/

BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS('CORE');
    DBMS_STATS.GATHER_SCHEMA_STATS('CRM');
END;
/

-- Users: a read-only one DAWAM should be given, and one that can write (the warning).
CREATE USER dawam_reader IDENTIFIED BY "reader-secret"
/
CREATE USER dawam_writer IDENTIFIED BY "writer-secret"
/
GRANT CREATE SESSION TO dawam_reader, dawam_writer
/
BEGIN
    FOR o IN (SELECT owner, object_name FROM all_objects
              WHERE owner IN ('CORE', 'CRM', 'RESTRICTED')
                AND object_type IN ('TABLE', 'VIEW')) LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT ON "' || o.owner || '"."' || o.object_name
            || '" TO dawam_reader, dawam_writer';
    END LOOP;
    FOR o IN (SELECT owner, object_name FROM all_objects
              WHERE owner = 'CORE' AND object_type IN ('FUNCTION', 'PROCEDURE')) LOOP
        EXECUTE IMMEDIATE 'GRANT EXECUTE ON "' || o.owner || '"."' || o.object_name
            || '" TO dawam_reader, dawam_writer';
    END LOOP;
END;
/
GRANT INSERT, UPDATE ON core.customers TO dawam_writer
/
